services:
  # PostgreSQL Database
  ecom-postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: ecom-postgres

  # Redis Cache
  ecom-redis:
    extends:
      file: ./services/redis/docker-compose.yml
      service: ecom-redis

  # RabbitMQ
  ecom-rabbitmq:
    extends:
      file: ./services/rabbitmq/docker-compose.yml
      service: ecom-rabbitmq

  # Elasticsearch
  ecom-elasticsearch:
    extends:
      file: ./services/elasticsearch/docker-compose.yml
      service: ecom-elasticsearch

  # Kibana
  ecom-kibana:
    extends:
      file: ./services/kibana/docker-compose.yml
      service: ecom-kibana

  # PgAdmin
  ecom-pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yml
      service: ecom-pgadmin

volumes:
  ecom_postgres_data:
    driver: local
  ecom_redis_data:
    driver: local
  ecom_rabbitmq_data:
    driver: local
  ecom_pgadmin_data:
    driver: local
  ecom_elasticsearch_data:
    driver: local

networks:
  ecom-network:
    external: true