services:
  ecom-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecom-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8081:80'
    volumes:
      - ecom_pgadmin_data:/var/lib/pgadmin
      - ./servers-dev.json:/pgadmin4/servers.json:ro
    networks:
      - ecom-network
    depends_on:
      - ecom-postgres

volumes:
  ecom_pgadmin_data:
    external: true

networks:
  ecom-network:
    external: true