version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ecom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DEV_USER: ${POSTGRES_DEV_USER}
      POSTGRES_DEV_PASSWORD: ${POSTGRES_DEV_PASSWORD}
    ports:
      - '5443:5432'
    volumes:
      - ecom_postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - ecom-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_ADMIN_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ecom_postgres_data:
    external: true

networks:
  ecom-network:
    external: true