version: "3.8"

services:
  ecom-postgres:
    image: postgres:15-alpine
    container_name: ecom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5443:5432'
    volumes:
      - ecom_postgres_data:/var/lib/postgresql/data
      # primary init scripts (moved to setup/)
      - ./setup:/docker-entrypoint-initdb.d:ro
      # keep original init files available as backup
      - ./init:/docker-entrypoint-initdb.d-local:ro
    networks:
      - ecom-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ecom_postgres_data:
    external: true

networks:
  ecom-network:
    external: true