services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_ADMIN_PASSWORD}
      - ELASTICSEARCH_ADMIN_PASSWORD=${ELASTICSEARCH_ADMIN_PASSWORD}
      - ELASTICSEARCH_DEV_PASSWORD=${ELASTICSEARCH_DEV_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ecom_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - '9201:9200'
    networks:
      - ecom-network
    healthcheck:
      test: ['CMD', 'curl', '-u', 'elastic:${ELASTICSEARCH_ADMIN_PASSWORD}', '-f', 'http://localhost:9200/_cluster/health']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  ecom_elasticsearch_data:
    external: true

networks:
  ecom-network:
    external: true