version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: ecom-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5602:5601'
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - ecom-network

networks:
  ecom-network:
    external: true